version: "3.8"

services:
  app:
    build: ./frontend
    ports:
      - "80:5173"
    volumes:
      - ./frontend/src:/app/src
    environment:
      VITE_API_URL: http://api:3000
    networks:
      - app-network

  api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_URL: mongodb://db/gamify
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mongo:5.0.19-focal
    ports:
      - "27017:27017"
    volumes:
      - gamify:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  gamify:
  
